{% set name = "secondarycoolantprops" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 208edf1256b44267577d9aaf023e7ee34cc3f0d764379282427a0e8883dbc236

build:
  entry_points:
    - scprop=scp.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - scp
    - pip
  run:
    - python >={{ python_min }}
    - click

test:
  imports:
    - scp
  commands:
    - pip check
    - scprop --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mitchute/SecondaryCoolantProps
  summary: A collection of secondary coolant fluid property functions and classes
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wouterpeere
