{% set name = "secondarycoolantprops" %}
{% set version = "1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35928ac70bb1881c162790f06ad82c58801b535ef95a7c5f66480a2bf6d6a830

build:
  entry_points:
    - scprop=scp.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }}
    - click

test:
  imports:
    - scp
  commands:
    - pip check
    - scprop --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mitchute/SecondaryCoolantProps
  summary: A collection of secondary coolant fluid property functions and classes
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wouterpeere
